name: Docker build on push
env:
        DOCKER_CLI_EXPERIMENTAL: enabled
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true

on:
    push:
        branches:
            - master

jobs:
        build:
                runs-on: ubuntu-18.04
                name: Build and push all the stuff defined in this repo
                steps:
                        - name: Checkout repo
                          uses: actions/checkout@v2

                        - name: Set env variables
                          run: |
                                  echo "::set-env name=BRANCH::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')"
                                  echo "::set-env name=SHORTSHA::$(git rev-parse --short HEAD)"
                                  echo "::set-env name=DOCKER_HUB_REPO::joinmarket"
                                  echo "::set-env name=DOCKER_USERNAME::${{ secrets.DOCKER_USERNAME }}"
                                  echo "::set-env name=DOCKER_PASSWORD::${{ secrets.DOCKER_PASSWORD }}"
                                  echo "::set-env name=MAINTAINER_USER::${{ secrets.MAINTAINER_USER }}"
                                  echo "::set-env name=MAINTAINER_TOKEN::${{ secrets.MAINTAINER_TOKEN }}"

                        - name: Show set env variables
                          run: |
                                  printf "    BRANCH: %s\n"  "$BRANCH"
                                  printf "    SHORTSHA: %s\n"  "$SHORTSHA"
                                  printf "    REPO: %s\n" "$GITHUB_REPOSITORY"
                                  printf "    COMMIT ID: %s\n" "$GITHUB_SHA"
                                  printf "    DOCKER REPO: %s\n" "$DOCKER_HUB_REPO"
                                  printf "    GITHUB_ACTOR: %s\n" "$GITHUB_ACTOR"
                                  printf "    GITHUB_REPOSITORY: %s\n" "$GITHUB_REPOSITORY"

                        - name: Login to Docker Hub with specified username
                          run: |
                                  if [[ ! -z $DOCKER_PASSWORD ]] && [[ ! -z $DOCKER_USERNAME ]]; then 
                                    echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
                                  else
                                    echo "DOCKER_USERNAME and DOCKER_PASSOWRD must be set!"
                                    exit 1
                                  fi

                        - name: Setup Docker buildx action
                          uses: crazy-max/ghaction-docker-buildx@v1
                          id: buildx
                          with:
                                  buildx-version: latest
                                  qemu-version: latest

                        - name: Show available Docker buildx platforms
                          run: echo ${{ steps.buildx.outputs.platforms }}

                        - name: Cache Docker layers
                          uses: actions/cache@v2
                          id: cache
                          with:
                              path: /tmp/.buildx-cache
                              key: ${{ runner.os }}-buildx-${{ github.sha }}
                              restore-keys: |
                                  ${{ runner.os }}-buildx-

                        - name: Build against master
                          run: |
                                  docker buildx build \
                                  --cache-from "type=local,src=/tmp/.buildx-cache" \
                                  --cache-to "type=local,dest=/tmp/.buildx-cache" \
                                  --platform linux/amd64,linux/arm64,linux/arm/v7 \
                                  --tag ${{ secrets.DOCKER_HUB_USER }}/$DOCKER_HUB_REPO:master-$SHORTSHA \
                                  --output "type=registry" .

                        - name: Build against latest tag
                          run: |
                                  docker buildx build \
                                  --cache-from "type=local,src=/tmp/.buildx-cache" \
                                  --cache-to "type=local,dest=/tmp/.buildx-cache" \
                                  --platform linux/amd64,linux/arm64,linux/arm/v7 \
                                  --tag ${{ secrets.DOCKER_HUB_USER }}/$DOCKER_HUB_REPO:latest \
                                  --output "type=registry" .

                        - name: Login and push (master to GHCR with MAINTAINER_USER and MAINTAINER_TOKEN if exists
                          run: |
                                  if [[ ! -z $MAINTAINER_TOKEN ]] && [[ ! -z $MAINTAINER_USER ]]; then  
                                        echo "$secrets.MAINTAINER_TOKEN" | docker login https://ghcr.io -u "$MAINTAINER_USER" --password-stdin
                                        docker buildx build \
                                                --cache-from "type=local,src=/tmp/.buildx-cache" \
                                                --cache-to "type=local,dest=/tmp/.buildx-cache" \
                                                --platform linux/amd64,linux/arm64,linux/arm/v7 \
                                                --tag ghcr.io/${{ secrets.DOCKER_HUB_USER }}/$DOCKER_HUB_REPO:master-$SHORTSHA \
                                                --output "type=registry" .
                                        docker buildx build \
                                                --cache-from "type=local,src=/tmp/.buildx-cache" \
                                                --cache-to "type=local,dest=/tmp/.buildx-cache" \
                                                --platform linux/amd64,linux/arm64,linux/arm/v7 \
                                                --tag ghcr.io/${{ secrets.DOCKER_HUB_USER }}/$DOCKER_HUB_REPO:latest \
                                                --output "type=registry" .                                                 
                                  else
                                        echo "MAINTAINER_TOKEN and MAINTAINER_USER do no exist! Skipping!"
                                  fi
  

